---

- hosts: tag_Name_{{ sit_servername }}
  sudo: yes
  roles:
    - { role: terminate server, server_region: "{{ sit_region }}" }

- hosts: tag_Name_{{ Prod_Server_Name }}
  sudo: yes
  roles:
    - { role: configure server, port: "{{ portnumber }}" }
    - { role: run application, artifact_path: "{{ artifact_path }}", app_name: "{{ app_name }}" }
