---
- hosts: tag_Name_{{ servername }}
  sudo: yes
  roles:
    - { role: terminate server, server_region: "{{ region }}" }
    - { role: cleanup , cleanup: "{{ cleanup }}", server_key_name: "{{ key_name }}", server_region: "{{ region }}", server_key_path: "{{ key_path }}", server_security_group: "{{ security_group }}", server_security_group_description: "{{ security_group_description}}",when: cleanup == 'true' }
