---

- name: get process id for the running application
  shell: lsof -t -i:{{port}}
  ignore_errors: yes
  register: pid
  
- name: kill the application
  shell: kill {{pid.stdout}}  
  when: pid.stdout != ""

- name: remove artifact
  file:
    state: absent
    path: "/artifact/aviva.war"
