---

- name: copy artifact
  copy:
    src={{ artifact_path }}
    dest=/artifact/{{ app_name }}
    owner=root
    group=root
    mode=0777
    
- name: run application
  shell: nohup java -jar /artifact/{{ app_name }} &