---

- name: Terminate The Inaccessible Server
  ec2:
    region: "{{ item.region }}"
    instance_ids: "{{ item.id }}"
    wait: true
    state: absent
  listen: Wait until SSH is available
    
- name: Remove the key pair
  ec2_key:
    name: "{{ item.key_name }}"
    region: "{{ item.region }}"
    state: absent
  listen: Wait until SSH is available
    
- name: Remove the local key pair
  file:
    path: "{{ server_key_path }}{{ server_key_name }}.pem"
    state: absent
  listen: Wait until SSH is available
    
- name: Remove Security Group
  ec2_group:
    group_id: "{{ item.groups[0] }}"
    region: "{{ item.region }}"
    state: absent
  listen: Wait until SSH is available