---

- name: copy artifact
  copy:
    src={{ artifact_path }}
    dest=/artifact/{{ app_name }}
    owner=root
    group=root
    mode=0777
    
- name: run application
  shell: nohup java -jar /artifact/{{ app_name }} &
    
- name: Install git
  apt: name=git state=present
  
- name: Create test directory
  file:
    path=/avivaTest
    state=directory
    owner=root
    group=root
    mode=0777

- name: Create directory for phantomJs
  file:
    path=/phantomjs
    state=directory
    owner=root
    group=root
    mode=0777

- name: Download phantomjs
  get_url:
    url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest=/phantomjs
    mode=0777

- name: untar Phantomjs
  unarchive:
    src: /phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /phantomjs/
    remote_src: true

- name: Clone git test repository
  git:
    repo="{{ functional_test_repo }}"
    dest=/avivaTest
    clone=yes
    update=yes
    force=yes
    
- name: resolving dependency for libfontconfig
  apt: name=libfontconfig state=present
  
- name: run test
  shell: mvn test
  args:
    chdir: /avivaTest/
  ignore_errors: yes
    
- name: get test results
  fetch: 
    src: /avivaTest/target/surefire-reports/testng-results.xml
    dest: {{ funtional_test_report_path }}
    flat: yes