---

- name: copy artifact
  copy:
    src={{ artifact_path }}
    dest=/artifact/{{ app_name }}
    owner=root
    group=root
    mode=0777
    
- name: run application
  shell: nohup java -jar /artifact/{{ app_name }} &

- name: display var
  debug:
    msg: "tool var is {{ TOOL }}"
    
- name: Install git
  apt: name=git state=present
  when: TOOL == 'GitSCM'
  
- name: Install svn
  apt: name=subversion state=present
  when: TOOL == 'SubversionSCM'
  
- name: Create test directory
  file:
    path=/{{ TESTNAME }}
    state=directory
    owner=root
    group=root
    mode=0777
  when: TOOL == 'GitSCM'

- name: Create directory for phantomJs
  file:
    path=/phantomjs
    state=directory
    owner=root
    group=root
    mode=0777

- name: Download phantomjs
  get_url:
    url=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest=/phantomjs
    mode=0777

- name: untar Phantomjs
  unarchive:
    src: /phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /phantomjs/
    remote_src: true

- name: Clone git test repository
  git:
    repo="{{ functional_test_repo }}"
    dest=/{{ TESTNAME }}
    clone=yes
    update=yes
    force=yes
  when: TOOL == 'GitSCM"
  
- name: Clone svn test repository
  subversion: 
    repo: "{{ functional_test_repo }}"
    dest: /{{ TESTNAME }}
    username: "{{ USERNAME }}"
    password: "{{ PASS }}" 
  when: TOOL == 'SubversionSCM'
    
- name: resolving dependency for libfontconfig
  apt: name=libfontconfig state=present
  
- name: run test
  shell: mvn test
  args:
    chdir: /{{ TESTNAME }}/
  ignore_errors: yes
    
- name: get test results
  fetch: 
    src: /{{ TESTNAME }}/target/surefire-reports/testng-results.xml
    dest: "{{ funtional_test_report_path }}"
    flat: yes
