---

- name: Gather facts
  ec2_remote_facts:
    region: "{{ server_region }}"
    filters:
      instance-state-name: running
      "tag:Name": "{{ server_name }}"
  register: info
  
- name: setfact
  set_fact:
    serverexists: no
  when: info.instances[0] is not defined
  
- name: setfact
  set_fact:
    serverexists: yes
  when: info.instances[0] is defined
  
- name: display fact
  debug:
    var: serverexists
  
