---

- tasks:
  - name: Gather facts
    ec2_remote_facts:
      region: {{ server_region }}
      filters:
        instance-state-name: running
        "tag:name": "{{ server_name }}"
    register: info
    

  - name: returning status if server exists
    set_facts:
      serverexists: yes
    when: info.instances[0] is defined
    
  - name: returning status if the server does not exist
    set_facts:
      serverexists: no
    when: info.instances[0] is not defined